// Code generated by "stringer -type=TokenType -trimprefix Token"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TokenEOF-0]
	_ = x[TokenSymbol-1]
	_ = x[TokenNumber-2]
	_ = x[TokenLParen-3]
	_ = x[TokenRParen-4]
}

const _TokenType_name = "EOFSymbolNumberLParenRParen"

var _TokenType_index = [...]uint8{0, 3, 9, 15, 21, 27}

func (i TokenType) String() string {
	if i < 0 || i >= TokenType(len(_TokenType_index)-1) {
		return "TokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[i]:_TokenType_index[i+1]]
}
